version: "3.9"

services:
  # ---------------- HDFS ----------------
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"   # Web UI
      - "9000:9000"   # HDFS NameNode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - bigdata-net

  # ---------------- Spark ----------------
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    restart: always
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    ports:
      - "7077:7077"   # Spark master
      - "8080:8080"   # Spark master web UI
    volumes:
      - ./app:/opt/spark-apps
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./target/scala-2.12:/opt/spark-apps
      - ./data:/data
      - ./output:/output 
    networks:
      - bigdata-net

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark worker web UI
    volumes:
      - ./app:/opt/spark-apps
      - ./hadoop-config:/opt/hadoop/etc/hadoop
    networks:
      - bigdata-net

  # ---------------- JupyterLab ----------------
  jupyterlab:
    build: ./jupyterlab
    container_name: jupyterlab
    ports:
      - "8888:8888"
      - "4040-4050:4040-4050"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./data:/data
      - ./output:/output 
    depends_on:
      - spark-master
      - namenode
    networks:
      - bigdata-net

volumes:
  hdfs-namenode:
  hdfs-datanode:

networks:
  bigdata-net:
    driver: bridge